// <auto-generated />
using System;
using HyperCar.DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HyperCar.DAL.Migrations
{
    [DbContext(typeof(HyperCarDbContext))]
    partial class HyperCarDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HyperCar.DAL.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Avatar")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBannedFromBooking")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("NoShowCount")
                        .HasColumnType("int");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber2")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("HyperCar.DAL.Entities.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Logo")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "France",
                            CreatedDate = new DateTime(2026, 3, 22, 12, 48, 38, 324, DateTimeKind.Utc).AddTicks(7718),
                            Description = "French luxury hypercar manufacturer",
                            IsActive = true,
                            Name = "Bugatti"
                        },
                        new
                        {
                            Id = 2,
                            Country = "Sweden",
                            CreatedDate = new DateTime(2026, 3, 22, 12, 48, 38, 324, DateTimeKind.Utc).AddTicks(7777),
                            Description = "Swedish hypercar manufacturer",
                            IsActive = true,
                            Name = "Koenigsegg"
                        },
                        new
                        {
                            Id = 3,
                            Country = "Italy",
                            CreatedDate = new DateTime(2026, 3, 22, 12, 48, 38, 324, DateTimeKind.Utc).AddTicks(7779),
                            Description = "Italian hypercar manufacturer",
                            IsActive = true,
                            Name = "Pagani"
                        },
                        new
                        {
                            Id = 4,
                            Country = "United Kingdom",
                            CreatedDate = new DateTime(2026, 3, 22, 12, 48, 38, 324, DateTimeKind.Utc).AddTicks(7780),
                            Description = "British supercar manufacturer",
                            IsActive = true,
                            Name = "McLaren"
                        },
                        new
                        {
                            Id = 5,
                            Country = "Italy",
                            CreatedDate = new DateTime(2026, 3, 22, 12, 48, 38, 324, DateTimeKind.Utc).AddTicks(7782),
                            Description = "Italian luxury sports car manufacturer",
                            IsActive = true,
                            Name = "Ferrari"
                        },
                        new
                        {
                            Id = 6,
                            Country = "Italy",
                            CreatedDate = new DateTime(2026, 3, 22, 12, 48, 38, 324, DateTimeKind.Utc).AddTicks(7783),
                            Description = "Italian luxury sports car manufacturer",
                            IsActive = true,
                            Name = "Lamborghini"
                        },
                        new
                        {
                            Id = 7,
                            Country = "Croatia",
                            CreatedDate = new DateTime(2026, 3, 22, 12, 48, 38, 324, DateTimeKind.Utc).AddTicks(7785),
                            Description = "Croatian electric hypercar manufacturer",
                            IsActive = true,
                            Name = "Rimac"
                        },
                        new
                        {
                            Id = 8,
                            Country = "United Kingdom",
                            CreatedDate = new DateTime(2026, 3, 22, 12, 48, 38, 324, DateTimeKind.Utc).AddTicks(7786),
                            Description = "British luxury car manufacturer",
                            IsActive = true,
                            Name = "Aston Martin"
                        });
                });

            modelBuilder.Entity("HyperCar.DAL.Entities.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Acceleration")
                        .HasColumnType("decimal(5,2)");

                    b.Property<double>("AverageRating")
                        .HasColumnType("float");

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Engine")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("HorsePower")
                        .HasColumnType("int");

                    b.Property<string>("ImageGallery")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<decimal>("TopSpeed")
                        .HasColumnType("decimal(8,2)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("Category");

                    b.HasIndex("IsActive");

                    b.HasIndex("Name");

                    b.HasIndex("Price");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Acceleration = 2.4m,
                            AverageRating = 0.0,
                            BrandId = 1,
                            Category = "HyperCar",
                            CreatedDate = new DateTime(2026, 3, 22, 12, 48, 38, 324, DateTimeKind.Utc).AddTicks(7844),
                            Description = "The Bugatti Chiron Super Sport is the ultimate expression of speed and luxury.",
                            Engine = "8.0L Quad-Turbo W16",
                            HorsePower = 1578,
                            ImageUrl = "/images/cars/chiron.jpg",
                            IsActive = true,
                            Name = "Chiron Super Sport",
                            Price = 3900000m,
                            Stock = 3,
                            TopSpeed = 440m
                        },
                        new
                        {
                            Id = 2,
                            Acceleration = 2.5m,
                            AverageRating = 0.0,
                            BrandId = 2,
                            Category = "HyperCar",
                            CreatedDate = new DateTime(2026, 3, 22, 12, 48, 38, 324, DateTimeKind.Utc).AddTicks(7870),
                            Description = "The fastest Koenigsegg ever made, designed for maximum speed.",
                            Engine = "5.0L Twin-Turbo V8",
                            HorsePower = 1600,
                            ImageUrl = "/images/cars/jesko.jpg",
                            IsActive = true,
                            Name = "Jesko Absolut",
                            Price = 3400000m,
                            Stock = 2,
                            TopSpeed = 531m
                        },
                        new
                        {
                            Id = 3,
                            Acceleration = 2.7m,
                            AverageRating = 0.0,
                            BrandId = 3,
                            Category = "HyperCar",
                            CreatedDate = new DateTime(2026, 3, 22, 12, 48, 38, 324, DateTimeKind.Utc).AddTicks(7875),
                            Description = "Track-focused masterpiece from Pagani with a naturally aspirated V12.",
                            Engine = "6.0L NA V12",
                            HorsePower = 850,
                            ImageUrl = "/images/cars/huayra.jpg",
                            IsActive = true,
                            Name = "Huayra R",
                            Price = 3100000m,
                            Stock = 5,
                            TopSpeed = 370m
                        },
                        new
                        {
                            Id = 4,
                            Acceleration = 2.5m,
                            AverageRating = 0.0,
                            BrandId = 4,
                            Category = "HyperGT",
                            CreatedDate = new DateTime(2026, 3, 22, 12, 48, 38, 324, DateTimeKind.Utc).AddTicks(7952),
                            Description = "McLaren's fastest car ever — a hyper-GT with a central driving position.",
                            Engine = "4.0L Twin-Turbo V8 Hybrid",
                            HorsePower = 1055,
                            ImageUrl = "/images/cars/speedtail.jpg",
                            IsActive = true,
                            Name = "Speedtail",
                            Price = 2250000m,
                            Stock = 4,
                            TopSpeed = 403m
                        },
                        new
                        {
                            Id = 5,
                            Acceleration = 2.5m,
                            AverageRating = 0.0,
                            BrandId = 5,
                            Category = "SuperCar",
                            CreatedDate = new DateTime(2026, 3, 22, 12, 48, 38, 324, DateTimeKind.Utc).AddTicks(7956),
                            Description = "Ferrari's first plug-in hybrid, blending extreme performance with innovation.",
                            Engine = "4.0L Twin-Turbo V8 Hybrid",
                            HorsePower = 986,
                            ImageUrl = "/images/cars/sf90.jpg",
                            IsActive = true,
                            Name = "SF90 Stradale",
                            Price = 625000m,
                            Stock = 8,
                            TopSpeed = 340m
                        },
                        new
                        {
                            Id = 6,
                            Acceleration = 2.5m,
                            AverageRating = 0.0,
                            BrandId = 6,
                            Category = "SuperCar",
                            CreatedDate = new DateTime(2026, 3, 22, 12, 48, 38, 324, DateTimeKind.Utc).AddTicks(7960),
                            Description = "Lamborghini's V12 hybrid flagship with 1015 combined horsepower.",
                            Engine = "6.5L NA V12 Hybrid",
                            HorsePower = 1015,
                            ImageUrl = "/images/cars/revuelto.jpg",
                            IsActive = true,
                            Name = "Revuelto",
                            Price = 608358m,
                            Stock = 6,
                            TopSpeed = 350m
                        },
                        new
                        {
                            Id = 7,
                            Acceleration = 1.85m,
                            AverageRating = 0.0,
                            BrandId = 7,
                            Category = "Electric HyperCar",
                            CreatedDate = new DateTime(2026, 3, 22, 12, 48, 38, 324, DateTimeKind.Utc).AddTicks(7963),
                            Description = "The world's fastest production electric hypercar.",
                            Engine = "Quad Electric Motors",
                            HorsePower = 1914,
                            ImageUrl = "/images/cars/nevera.jpg",
                            IsActive = true,
                            Name = "Nevera",
                            Price = 2400000m,
                            Stock = 3,
                            TopSpeed = 412m
                        },
                        new
                        {
                            Id = 8,
                            Acceleration = 2.5m,
                            AverageRating = 0.0,
                            BrandId = 8,
                            Category = "HyperCar",
                            CreatedDate = new DateTime(2026, 3, 22, 12, 48, 38, 324, DateTimeKind.Utc).AddTicks(7970),
                            Description = "Aston Martin and Red Bull Racing's F1-inspired hypercar.",
                            Engine = "6.5L NA V12 + Electric",
                            HorsePower = 1160,
                            ImageUrl = "/images/cars/valkyrie.jpg",
                            IsActive = true,
                            Name = "Valkyrie",
                            Price = 3500000m,
                            Stock = 2,
                            TopSpeed = 402m
                        });
                });

            modelBuilder.Entity("HyperCar.DAL.Entities.ConversationHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AiResponse")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SessionId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserMessage")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedDate");

                    b.HasIndex("UserId");

                    b.ToTable("ConversationHistories");
                });

            modelBuilder.Entity("HyperCar.DAL.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ReceiverName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ReceiverPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ShippingAddress")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("ShippingFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserAction")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedDate");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("HyperCar.DAL.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("HyperCar.DAL.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BankCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TransactionRef")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("VnPayResponseCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("VnPayResponseData")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.HasIndex("TransactionRef");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("HyperCar.DAL.Entities.ReportSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("JsonData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReportDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ReportDate", "Type");

                    b.ToTable("ReportSnapshots");
                });

            modelBuilder.Entity("HyperCar.DAL.Entities.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AiFlagReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrls")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAiFlagged")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEdited")
                        .HasColumnType("bit");

                    b.Property<int?>("OrderItemId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("OrderItemId")
                        .IsUnique()
                        .HasFilter("[OrderItemId] IS NOT NULL");

                    b.HasIndex("UserId", "CarId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("HyperCar.DAL.Entities.Shipping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ApiResponseData")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DistrictId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EstimatedDelivery")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Fee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ProvinceId")
                        .HasColumnType("int");

                    b.Property<string>("ReceiverName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ReceiverPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TrackingCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("WardCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.HasIndex("TrackingCode");

                    b.ToTable("Shippings");
                });

            modelBuilder.Entity("HyperCar.DAL.Entities.Showroom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Showrooms");
                });

            modelBuilder.Entity("HyperCar.DAL.Entities.TestDriveBooking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminResponse")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ShowroomId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("ShowroomId");

                    b.HasIndex("Status");

                    b.HasIndex("CarId", "ScheduledDate")
                        .IsUnique()
                        .HasFilter("[Status] != 3");

                    b.ToTable("TestDriveBookings");
                });

            modelBuilder.Entity("HyperCar.DAL.Entities.TransactionHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChangedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("StatusFrom")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StatusTo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedDate");

                    b.HasIndex("OrderId");

                    b.ToTable("TransactionHistories");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "admin-role-id",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "customer-role-id",
                            Name = "Customer",
                            NormalizedName = "CUSTOMER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("HyperCar.DAL.Entities.Car", b =>
                {
                    b.HasOne("HyperCar.DAL.Entities.Brand", "Brand")
                        .WithMany("Cars")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("HyperCar.DAL.Entities.ConversationHistory", b =>
                {
                    b.HasOne("HyperCar.DAL.Entities.ApplicationUser", "User")
                        .WithMany("ConversationHistories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("HyperCar.DAL.Entities.Order", b =>
                {
                    b.HasOne("HyperCar.DAL.Entities.ApplicationUser", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HyperCar.DAL.Entities.OrderItem", b =>
                {
                    b.HasOne("HyperCar.DAL.Entities.Car", "Car")
                        .WithMany("OrderItems")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HyperCar.DAL.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("HyperCar.DAL.Entities.Payment", b =>
                {
                    b.HasOne("HyperCar.DAL.Entities.Order", "Order")
                        .WithOne("Payment")
                        .HasForeignKey("HyperCar.DAL.Entities.Payment", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("HyperCar.DAL.Entities.Review", b =>
                {
                    b.HasOne("HyperCar.DAL.Entities.Car", "Car")
                        .WithMany("Reviews")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HyperCar.DAL.Entities.OrderItem", "OrderItem")
                        .WithOne("Review")
                        .HasForeignKey("HyperCar.DAL.Entities.Review", "OrderItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HyperCar.DAL.Entities.ApplicationUser", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("OrderItem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HyperCar.DAL.Entities.Shipping", b =>
                {
                    b.HasOne("HyperCar.DAL.Entities.Order", "Order")
                        .WithOne("Shipping")
                        .HasForeignKey("HyperCar.DAL.Entities.Shipping", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("HyperCar.DAL.Entities.TestDriveBooking", b =>
                {
                    b.HasOne("HyperCar.DAL.Entities.ApplicationUser", "User")
                        .WithMany("TestDriveBookings")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HyperCar.DAL.Entities.Car", "Car")
                        .WithMany("TestDriveBookings")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HyperCar.DAL.Entities.Showroom", "Showroom")
                        .WithMany("TestDriveBookings")
                        .HasForeignKey("ShowroomId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Car");

                    b.Navigation("Showroom");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HyperCar.DAL.Entities.TransactionHistory", b =>
                {
                    b.HasOne("HyperCar.DAL.Entities.Order", "Order")
                        .WithMany("TransactionHistories")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("HyperCar.DAL.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("HyperCar.DAL.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HyperCar.DAL.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("HyperCar.DAL.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HyperCar.DAL.Entities.ApplicationUser", b =>
                {
                    b.Navigation("ConversationHistories");

                    b.Navigation("Orders");

                    b.Navigation("Reviews");

                    b.Navigation("TestDriveBookings");
                });

            modelBuilder.Entity("HyperCar.DAL.Entities.Brand", b =>
                {
                    b.Navigation("Cars");
                });

            modelBuilder.Entity("HyperCar.DAL.Entities.Car", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("Reviews");

                    b.Navigation("TestDriveBookings");
                });

            modelBuilder.Entity("HyperCar.DAL.Entities.Order", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("Payment");

                    b.Navigation("Shipping");

                    b.Navigation("TransactionHistories");
                });

            modelBuilder.Entity("HyperCar.DAL.Entities.OrderItem", b =>
                {
                    b.Navigation("Review");
                });

            modelBuilder.Entity("HyperCar.DAL.Entities.Showroom", b =>
                {
                    b.Navigation("TestDriveBookings");
                });
#pragma warning restore 612, 618
        }
    }
}
